# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script: []
pages:
  script:
    - npm ci
    - npm run build
    - mv public public-vue
    - mv dist public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec
      gzip -f -k {} \;
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
